# Generated by Django 3.2.5 on 2021-10-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='job',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
