# Generated by Django 3.2.5 on 2021-11-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20211116_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='time_period',
        ),
    ]
