# Generated by Django 3.2.5 on 2021-11-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_experience_time_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Candidate',
            new_name='candidate',
        ),
    ]
