# Generated by Django 3.2.5 on 2021-11-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_candidate_user'),
        ('jobs', '0007_rename_candidate_experience_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidate',
        ),
        migrations.CreateModel(
            name='Candidateship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='users.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.job')),
            ],
        ),
    ]
