# Generated by Django 3.2.5 on 2021-11-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20211119_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidateship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.candidateship'),
        ),
    ]
