# Generated by Django 3.2.5 on 2021-11-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_interview_candidateship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateship',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateship',
            name='job',
        ),
    ]
