# Generated by Django 3.2.5 on 2021-11-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211122_1114'),
        ('jobs', '0010_auto_20211122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidateship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='users.candidateship'),
        ),
        migrations.DeleteModel(
            name='Candidateship',
        ),
    ]
