# Generated by Django 3.2.5 on 2021-11-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20211122_1508'),
        ('jobs', '0012_auto_20211122_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateship',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateship', to='users.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateship',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateship', to='jobs.job'),
        ),
    ]
