# Generated by Django 3.2.5 on 2021-11-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20211122_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidateship',
        ),
    ]
