# Generated by Django 3.2.5 on 2021-11-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_candidate_jobs'),
        ('jobs', '0015_interview_candidateship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidateship',
        ),
        migrations.DeleteModel(
            name='Candidateship',
        ),
    ]
