# Generated by Django 3.2.5 on 2021-11-23 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_candidate_jobs'),
        ('jobs', '0016_auto_20211123_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidateship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateship', to='users.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateship', to='jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='candidateship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.candidateship'),
        ),
    ]
