# Generated by Django 3.2.5 on 2021-10-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
