# Generated by Django 3.2.5 on 2021-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211025_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CANDIDATE', 'CANDIDATE'), ('INTERVIEWER', 'INTERVIEWER'), ('ADMIN', 'ADMIN')], default='ADMIN', max_length=50),
        ),
    ]
