# Generated by Django 3.2.5 on 2021-10-25 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211025_1621'),
        ('users', '0006_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managing_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('USER', 'USER')], default='USER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Interviewer',
        ),
    ]
