# Generated by Django 3.2.5 on 2021-10-25 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211025_1621'),
        ('users', '0007_auto_20211025_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FilePathField(blank=True, null=True)),
                ('jobs', models.ManyToManyField(related_name='candidates', to='jobs.Job')),
                ('user', models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role', models.CharField(max_length=200)),
                ('user', models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
