# Generated by Django 3.2.5 on 2021-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20211119_1654'),
        ('users', '0012_alter_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(related_name='candidates', through='jobs.Candidateship', to='jobs.Job'),
        ),
    ]
