# Generated by Django 3.2.5 on 2021-11-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211122_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='jobs',
        ),
    ]
