# Generated by Django 3.2.5 on 2021-11-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_candidate_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateship',
            name='job',
        ),
    ]
