# Generated by Django 3.2.5 on 2021-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20211122_1508'),
        ('users', '0024_candidate_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='jobs',
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(
                related_name='candidates', through='jobs.Candidateship', to='jobs.Job'),
        ),
        migrations.DeleteModel(
            name='Candidateship',
        ),
    ]
