# Generated by Django 3.2.5 on 2021-11-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_interview_candidateship'),
        ('users', '0027_alter_candidate_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(related_name='candidates', through='jobs.Candidateship', to='jobs.Job'),
        ),
    ]
