# Generated by Django 3.2.5 on 2021-11-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20211123_0717'),
        ('users', '0029_remove_candidate_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='jobs',
            field=models.ManyToManyField(related_name='candidates', through='jobs.Candidateship', to='jobs.Job'),
        ),
    ]
